#!/usr/bin/env bash

echo "Building..."

spago build
pslua --foreign-path . --ps-output output --entry Data.Unfoldable --lua-output-file dist/Data.Unfoldable.lua 
pslua --foreign-path . --ps-output output --entry Data.Unfoldable1 --lua-output-file dist/Data.Unfoldable1.lua 
